version: '3'
services:

  # PHP Service
  app:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    image: cubesystems/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
        - dbdata:/var/lib/mysql/
    networks:
        - app-network

  # Redis Service
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Node Service
  node:
    build:
      context: .docker/node
      dockerfile: Dockerfile
    image: cubesystems/node
    container_name: node
    volumes:
      - ./:/var/www
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
